name: skiplist
description: A skiplist implementation in Dart.
version: 0.1.0
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-skiplist

dependencies:
  quiver_iterables: ">=1.0.0 <2.0.0"

dev_dependencies:
  test: '>=0.12.7 <0.13.0'
